sudo: required
services:
    - docker

before_install:
    - docker build -t janard/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true janard/docker-react npm test 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-862446914542"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
